### ISSUE TITLE
Create Django models based on MMDB Tables

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/MMDB#4]
Would like to import the following tables:

Harmonized_raw
harmonized_aggregate
source
substances
media

**Comment by fang-yan-csra** [comment]
mmdb schema documentation: 
[mmdb_schema_20210115.mwb.zip](https://github.com/HumanExposure/MMDB/files/5838000/mmdb_schema_20210115.mwb.zip)
